### ISSUE TITLE
Support for Cypress test generation

### ISSUE THREAD

**Issue by LifeIsStrange** [DeploySentinel/Recorder#5]
Make it happen, plz :)

**Comment by MikeShi42** [comment]
We've added Cypress support in 0.6.0 now available on Chrome and Firefox!

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2781687/159345253-91cf4609-a813-4a29-9317-3e81a32b4025.png">

Let us know if you have any feedback!

**Comment by LifeIsStrange** [comment]
OK this is amazing.
